### ISSUE TITLE
BearRiver broken when installing from Hackage

### ISSUE THREAD

**Issue by thalerjonathan** [ivanperez-keera/dunai#57]
When adding bearriver in my cabal file and running 'cabal install' (its within a sandbox) then I get these errors:

Preprocessing library bearriver-0.10.4...
[1 of 8] Compiling FRP.Yampa.VectorSpace ( src/FRP/Yampa/VectorSpace.hs, dist/dist-sandbox-5cbfec19/build/FRP/Yampa/VectorSpace.o )
[2 of 8] Compiling FRP.Yampa.Vector3 ( src/FRP/Yampa/Vector3.hs, dist/dist-sandbox-5cbfec19/build/FRP/Yampa/Vector3.o )
[3 of 8] Compiling FRP.Yampa.Vector2 ( src/FRP/Yampa/Vector2.hs, dist/dist-sandbox-5cbfec19/build/FRP/Yampa/Vector2.o )
[4 of 8] Compiling FRP.Yampa.AffineSpace ( src/FRP/Yampa/AffineSpace.hs, dist/dist-sandbox-5cbfec19/build/FRP/Yampa/AffineSpace.o )
[5 of 8] Compiling FRP.Yampa.Point2 ( src/FRP/Yampa/Point2.hs, dist/dist-sandbox-5cbfec19/build/FRP/Yampa/Point2.o )
[6 of 8] Compiling FRP.Yampa.Point3 ( src/FRP/Yampa/Point3.hs, dist/dist-sandbox-5cbfec19/build/FRP/Yampa/Point3.o )
[7 of 8] Compiling FRP.BearRiver    ( src/FRP/BearRiver.hs, dist/dist-sandbox-5cbfec19/build/FRP/BearRiver.o )

src/FRP/BearRiver.hs:18:1: error:
    Failed to load interface for ‘Control.Monad.Trans.MStreamF’
    Perhaps you meant
      Control.Monad.Trans.MSF (from dunai-0.3.0.0)
      Control.Monad.Trans.State (from transformers-0.5.2.0)
      Control.Monad.Trans.MSF.Maybe (from dunai-0.3.0.0)
    Use -v to see a list of the files searched for.

src/FRP/BearRiver.hs:24:1: error:
    Failed to load interface for ‘Data.MonadicStreamFunction.ArrowLoop’
    Perhaps you meant
      Data.MonadicStreamFunction.Async (from dunai-0.3.0.0)
      Data.MonadicStreamFunction.Core (from dunai-0.3.0.0)
      Data.MonadicStreamFunction.Parallel (from dunai-0.3.0.0)

To reproduce: 
1. create new folder and cd into it
2. run 'cabal init' (and follow all steps, create Main.hs)
3. run 'cabal sandbox init'
4. add 'bearriver' to dependencies in cabal file
5. run 'cabal install'

**Comment by thalerjonathan** [comment]
When cloning dunai from this repository and building bearriver into my sandbox using 'cabal install dunai/examples/bearriver/' it works fine.

**Comment by turion** [comment]
That's because the bearriver on hackage is outdated. @ivanperez-keera , can you publish the latest version? (API changed)

**Comment by ivanperez-keera** [comment]
Done.

**Comment by thalerjonathan** [comment]
@ivanperez-keera sorry, I just tried it, and I still get the following error:

```console
src/FRP/BearRiver.hs:26:1: error:
    Failed to load interface for ‘Data.MonadicStreamFunction.ArrowLoop’
    Perhaps you meant
      Data.MonadicStreamFunction.Async (from dunai-0.3.0.0)
      Data.MonadicStreamFunction.Core (from dunai-0.3.0.0)
      Data.MonadicStreamFunction.Parallel (from dunai-0.3.0.0)

**Comment by turion** [comment]
@thalerjonathan did you `cabal update`? And change your dependencies to `bearriver-0.10.4.1`?

**Comment by thalerjonathan** [comment]
Yes I did a ``cabal update`` and I also deleted my sandbox and created a new one. I didn't put constraints on the bearriver dependencies but it is clearly showing that ``bearriver-0.10.4.1`` is being installed. I also tried it with ``bearriver == 0.10.4.1`` and still the same error.

**Comment by turion** [comment]
Yes... somehow, https://github.com/ivanperez-keera/dunai/blob/develop/examples/bearriver/src/FRP/BearRiver.hs and http://hackage.haskell.org/package/bearriver-0.10.4.1/src/src/FRP/BearRiver.hs differ. I guess it's just an outdated bearriver version that was accidentally uploaded. Thanks for testing!

**Comment by ivanperez-keera** [comment]
My bad. I don't know exactly how, but I clearly uploaded an outdated version.

No matter: I'll deprecate that one, upload a new one asap, and upload a new version of Dunai to hackage.
